services:
  db:
    # the Docker image of postgres -- we're using the latest
    image: postgres:latest
    # The ports to expose to the host container
    # 5432 is the default port for Postgres
    ports:
        - "5432:5432"
    # If we accidentally kill the running container, Docker compose will restart it
    restart: always
    # The PostgresSQL Docker container uses the environment variables to read configuration, here we set the password.
    # - Do not store plaintext passwords in source control. We do so here as this is a builder
    environment:
      POSTGRES_PASSWORD: changeinprod!
